[tool.poetry]
name = "localstack"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.26.160"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
